routes/web.php
<?php

use App\Http\Middleware\SubscriptedMiddleware;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/access-denied', function () {
    return abort(403);
})->name("access-denied");
Route::get('/register', 'RegisterController@index')->name("register.index");
Route::get('/register/teologian', 'RegisterController@teologian')->name("register.teologian");
Route::post('/register/teologian', 'RegisterController@teologian_store')->name("register.teologian.store");
Route::get('/register/user', 'RegisterController@user')->name("register.user");
Route::post('/register/user', 'RegisterController@user_store')->name("register.user.store");
Route::post('/user/email/check', 'UserController@emailCheck')->name("user.email.check");
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/home/sermon/table', 'HomeController@sermon_table')->name('home.sermon.table');
    Route::post('/home/article/table', 'HomeController@article_table')->name('home.article.table');
    Route::post('/home/pengendalian/table', 'HomeController@pengendalian_table')->name('home.pengendalian.table');
   
    Route::post('/home/lainnya/table', 'HomeController@lainnya_table')->name('home.lainnya.table');
    Route::post('/home/peningkatan/table', 'HomeController@peningkatan')->name('home.peningkatan.table');
    Route::post('/home/bulletin/table', 'HomeController@bulletin_table')->name('home.bulletin.table');
    Route::post('/home/meeting-result/table', 'HomeController@meeting_result_table')->name('home.meeting-result.table');
    Route::post('/home/document/table', 'HomeController@document_table')->name('home.document.table');
    Route::post('/home/resolution/table', 'HomeController@resolution_table')->name('home.resolution.table');
    Route::post('/home/preview', 'HomeController@preview')->name('home.preview');

    Route::get('/account', 'AccountController@index')->name('account.index');
    Route::put('/account/update', 'AccountController@update')->name('account.update');
    Route::put('/account/password', 'AccountController@password')->name('account.password');
    Route::delete('/account/delete-picture', 'AccountController@delete_picture')->name('account.delete_picture');

    Route::resource('/user', 'UserController');
    Route::post('/user/table', 'UserController@table')->name('user.table');
    Route::post('/user/{id}/mark-biodata', 'UserController@mark_biodata')->name('user.mark-biodata');
    Route::delete('/user/delete_picture/{id}', 'UserController@delete_picture')->name('user.delete_picture');

    Route::post('/user/{id}/address/table', 'UserController@address_table')->name("user.address.table");
    Route::get("user/{id}/address/create", "UserController@address_create")->name("user.address.create");
    Route::post('/user/{id}/address/store', 'UserController@address_store')->name("user.address.store");
    Route::get("user/{id}/address/{address_id}/edit", "UserController@address_edit")->name("user.address.edit");
    Route::put('/user/{id}/address/{address_id}', 'UserController@address_update')->name("user.address.update");
    Route::delete('/user/{id}/address/{address_id}', 'UserController@address_destroy')->name("user.address.destroy");

    Route::post('/user/{id}/education/table', 'UserController@education_table')->name("user.education.table");
    Route::get("user/{id}/education/create", "UserController@education_create")->name("user.education.create");
    Route::post('/user/{id}/education/store', 'UserController@education_store')->name("user.education.store");
    Route::get("user/{id}/education/{education_id}/edit", "UserController@education_edit")->name("user.education.edit");
    Route::put('/user/{id}/education/{education_id}', 'UserController@education_update')->name("user.education.update");
    Route::delete('/user/{id}/education/{education_id}', 'UserController@education_destroy')->name("user.education.destroy");

    Route::post('/user/{id}/organization-experience/table', 'UserController@organization_experience_table')->name("user.organization-experience.table");
    Route::get("user/{id}/organization-experience/create", "UserController@organization_experience_create")->name("user.organization-experience.create");
    Route::post('/user/{id}/organization-experience/store', 'UserController@organization_experience_store')->name("user.organization-experience.store");
    Route::get("user/{id}/organization-experience/{organization_experience_id}/edit", "UserController@organization_experience_edit")->name("user.organization-experience.edit");
    Route::put('/user/{id}/organization-experience/{organization_experience_id}', 'UserController@organization_experience_update')->name("user.organization-experience.update");
    Route::delete('/user/{id}/organization-experience/{organization_experience_id}', 'UserController@organization_experience_destroy')->name("user.organization-experience.destroy");

    Route::post('/user/{id}/work-experience/table', 'UserController@work_experience_table')->name("user.work-experience.table");
    Route::get("user/{id}/work-experience/create", "UserController@work_experience_create")->name("user.work-experience.create");
    Route::post('/user/{id}/work-experience/store', 'UserController@work_experience_store')->name("user.work-experience.store");
    Route::get("user/{id}/work-experience/{work_experience_id}/edit", "UserController@work_experience_edit")->name("user.work-experience.edit");
    Route::put('/user/{id}/work-experience/{work_experience_id}', 'UserController@work_experience_update')->name("user.work-experience.update");
    Route::delete('/user/{id}/work-experience/{work_experience_id}', 'UserController@work_experience_destroy')->name("user.work-experience.destroy");

    Route::post('/user/{id}/experience/table', 'UserController@experience_table')->name("user.experience.table");
    Route::get("user/{id}/experience/create", "UserController@experience_create")->name("user.experience.create");
    Route::post('/user/{id}/experience/store', 'UserController@experience_store')->name("user.experience.store");
    Route::get("user/{id}/experience/{experience_id}/edit", "UserController@experience_edit")->name("user.experience.edit");
    Route::put('/user/{id}/experience/{experience_id}', 'UserController@experience_update')->name("user.experience.update");
    Route::delete('/user/{id}/experience/{experience_id}', 'UserController@experience_destroy')->name("user.experience.destroy");

    Route::post('/notification/read', 'NotificationController@read')->name("notification.read");
    Route::get('/notification', 'NotificationController@index')->name("notification.index");

    Route::resource('/role', 'RoleController');
    Route::post('/role/table', 'RoleController@table')->name("role.table");

    Route::resource('/language', 'LanguageController')->except(["show", "create"]);
    Route::post('/language/table', 'LanguageController@table')->name("language.table");


    Route::get('/file-manager', 'FileManagerController@index')->name('file-manager.index');

    Route::resource('/document', 'DocumentController');
    Route::post('/document/table', 'DocumentController@table')->name("document.table");

    Route::resource('/sermon', 'SermonController');
    Route::post('/sermon/table', 'SermonController@table')->name("sermon.table");

    Route::resource('/article', 'ArticleController');
    Route::post('/article/table', 'ArticleController@table')->name("article.table");

    Route::resource('/lainnya', 'LainnyaController');
    Route::post('/lainnya/table', 'LainnyaController@table')->name("lainnya.table");

    Route::resource('/pengendalian', 'PengendalianController');
    Route::post('/pengendalian/table', 'PengendalianController@table')->name("pengendalian.table");

    Route::resource('/peningkatan', 'PeningkatanController');
    Route::post('/peningkatan/table', 'PeningkatanController@table')->name("peningkatan.table");

    Route::resource('/bulletin', 'BulletinController');
    Route::post('/bulletin/table', 'BulletinController@table')->name("bulletin.table");

    Route::resource('/meeting-result', 'MeetingResultController');
    Route::post('/meeting-result/table', 'MeetingResultController@table')->name("meeting-result.table");

    Route::resource('/organization', 'OrganizationController')->except(["show", "create"]);
    Route::post('/organization/table', 'OrganizationController@table')->name("organization.table");

    Route::resource('/mui-title', 'MuiTitleController')->except(["show", "create"]);
    Route::post('/mui-title/table', 'MuiTitleController@table')->name("mui-title.table");

    Route::resource('/resolution', 'ResolutionController');
    Route::post('/resolution/table', 'ResolutionController@table')->name("resolution.table");

    Route::get('/region/regencies/{id}', 'RegionController@get_regencies')->name('region.regencies');
    Route::get('/region/districts/{id}', 'RegionController@get_districts')->name('region.districts');
    Route::get('/region/villages/{id}', 'RegionController@get_villages')->name('region.villages');
});

Route::get('instrumen', function(){

app/Models/Resolution.php
<?php

namespace App\Models;

use App\Traits\ModelUuids;
use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Resolution extends Model
{
    use ModelUuids, SoftDeletes;

    public function author()
    {
        return $this->belongsTo(User::class, "created_by", "id");
    }
}

app/Http/Controllers/ResolutionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Document;
use App\Models\Resolution;
use Illuminate\Http\Request;

class ResolutionController extends Controller
{
    public function __construct()
    {
        $this->_var = [
            "menu"  => "resolution",
            "title" => "Peningkatan",
            "icon"  => "fas fa-gavel",
        ];

        $this->_table = 'resolutions';
        $this->_list_users = dja_get_all_list(["table" => "users", "key" => "id", "val" => "name"]);
        $this->_list_content_types = [
            "file" => "File",
            "link" => "Link",
            "papers" => "Karya Tulis",
        ];

        $this->_col = [
            'title' => [
                'type'  => 'like',
                'title' => "Title",
                'required',
                'display' => [
                    'type' => 'link',
                    'link' => 'resolution/',
                    'id'   => 'id',
                ],
            ],
            'date' => [
                'type'  => 'from',
                'sub-type' => 'datetime',
                'title' => "Declaration Date",
                'required',
                'display' => [
                    'type' => 'link_date',
                    'link' => 'resolution/',
                    'id'   => 'id',
                ],
            ],
            'created_by' => [
                'type'  => 'option',
                'title' => "Created by",
                'data' => $this->_list_users,
                'required',
                'display' => [
                    'type' => 'link_option',
                    'link' => 'resolution/',
                    'id'   => 'id',
                ],
            ],
            'created_at' => [
                'type'  => 'from',
                'sub-type' => 'datetime',
                'title' => "Created at",
                'required',
                'display' => [
                    'type' => 'link_date',
                    'link' => 'resolution/',
                    'id'   => 'id',
                ],
            ],
            'content_type' => [
                'type'  => 'option',
                'title' => "Content Type",
                'data' => $this->_list_content_types,
                'required',
                'display' => [
                    'type' => 'link_option',
                    'link' => 'resolution/',
                    'id'   => 'id',
                ],
            ],
        ];

        $this->_query['column_search'] = $this->_col;
    }

    public function index()
    {
        have_permit('resolution.view');

        $data['menu']  = $this->_var['menu'];
        $data['title'] = _l($this->_var["title"]);
        $data['icon']  = $this->_var["icon"];

        $data['table'] = dja_table($this->_col, 'table table-hover table-striped my-table', 'mytable');

        return view('resolution.table', $data);
    }


    public function create()
    {
        have_permit('resolution.add');

        $data['menu']  = $this->_var['menu'];
        $data['title'] = _l($this->_var["title"]);
        $data['icon']  = $this->_var["icon"];

        $data['list_content_types'] = $this->_list_content_types;

        return view('resolution.form', $data);
    }

    public function store(Request $request)
    {
        have_permit('resolution.add');

        $request->validate([
            "title"  => 'required',
            "content_type" => 'required',
        ]);

        $target = new Resolution;
        $target->title = $request->title;
        $target->content_type = $request->content_type;
        $target->date = tgl_dt($request->date);
        $target->created_by = auth()->user()->id;
        $target->updated_by = auth()->user()->id;
        $target->save();

        if ($request->content_type == 'papers') {
            $target->content = $request->content;
        } else if ($request->content_type == "link") {
            $target->link = $request->link;
        } else if ($request->content_type == "file") {
            $file_name = time() . '_' . $request->file->getClientOriginalName();
            $request->file->move(public_path("uploads/documents"), $file_name);

            $doc = new Document;
            $doc->name = $request->title;
            $doc->link = url("/uploads/documents/$file_name");
            $doc->category = "resolution";
            $doc->relation_id = $target->id;
            $doc->created_by = auth()->user()->id;
            $doc->updated_by = auth()->user()->id;

            $doc->save();
        }

        $target->save();

        return redirect(route("resolution.index"))->with("alert-success", _l("data_saved_successfully"));
    }

    public function show($id)
    {
        have_permit('resolution.detail');

        $value = Resolution::find($id);

        $data['menu']  = $this->_var['menu'];
        $data['title'] = _l($this->_var["title"]);
        $data['icon']  = $this->_var["icon"];

        $data['list_content_types'] = $this->_list_content_types;

        $data['data']   = $value;

        if ($value->content_type == "file") {
            $data['document'] = Document::where(['category' => "resolution", "relation_id" => $value->id])->first();
        }

        return view('resolution.detail', $data);
    }

    public function edit($id)
    {
        have_permit('resolution.edit');

        $data['menu']  = $this->_var['menu'];
        $data['title'] = _l($this->_var["title"]);
        $data['icon']  = $this->_var["icon"];
        $data['data'] = Resolution::findOrFail($id);

        $data['list_content_types'] = $this->_list_content_types;

        return view('resolution.form', $data);
    }

    public function update($id, Request $request)
    {
        have_permit('resolution.edit');

        $request->validate([
            "title"  => 'required',
            "content_type" => 'required',
        ]);

        $target = Resolution::findOrFail($id);
        $target->title = $request->title;
        $target->content_type = $request->content_type;
        $target->date = tgl_dt($request->date);
        $target->updated_by = auth()->user()->id;
        $target->save();

        if ($request->content_type == 'papers') {
            $target->content = $request->content;
        } else if ($request->content_type == "link") {
            $target->link = $request->link;
        } else if ($request->content_type == "file" && $request->file) {
            $file_name = time() . '_' . $request->file->getClientOriginalName();
            $request->file->move(public_path("uploads/documents"), $file_name);

            $doc = Document::where(['relation_id' => $id, 'category' => 'resolution'])->first();

            if (!$doc) {
                $doc = new Document;
                $doc->created_by = auth()->user()->id;
            }

            $doc->name = $request->title;
            $doc->link = url("/uploads/documents/$file_name");
            $doc->category = "resolution";
            $doc->relation_id = $target->id;
            $doc->updated_by = auth()->user()->id;

            $doc->save();
        }

        $target->save();
        return redirect(route("resolution.show", $target->id))->with("alert-success", _l("data_changed_successfully"));
    }

    public function destroy($id)
    {
        have_permit('resolution.edit');

        $value = Resolution::findOrFail($id);
        $value->deleted_by = auth()->user()->id;
        $value->save();

        $value->delete($id);

        return redirect()->route('resolution.index')->with("alert-success",  _l("data_successfully_deleted"));
    }
}

resources/views/resolution/form.blade.php
@extends('layouts.master')

@section("breadcrumb")
{!! dja_breadcrumb([route("home") => _l("dashboard"), route("resolution.index") => $title, "" => _l('form')]) !!}
@endsection

@section('content')
<div class="container-fluid container-fixed-lg">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <form id="form-content" method="post" action="@if(isset($data)){{ route('resolution.update', $data->id) }}@else{{ route('resolution.store') }}@endif" role="form" class="myform" autocomplete="off" novalidate enctype="multipart/form-data">
                        @csrf
                        @if(isset($data))
                        @method("put")
                        @endif

                        <div class="row">
                            <div class="col-md-12">
                                <p class="text-blue-mandiri bold text-uppercase m-b-20"><i class="fas fa-bookmark text-yellow-mandiri"></i> {{ _l('form') }}</p>
                            </div>
                            <div class="col-md-12">
                                {!! dja_form_input(['type' => 'text', 'input_attr' => ['required' => 'required'], 'name' => 'title', 'label' => _l("title"), 'value' => isset($data) ? $data->title : ""]) !!}
                                <!-- {!! dja_form_input(['type' => 'text', 'input_attr' => ['required' => 'required'],'input_class' => 'datetimep ', 'name' => 'date', 'label' => _l("declaration date"), 'value' => isset($data) ? tgl_indo($data->date) : ""]) !!} -->
                                {!! dja_form_select(['name' => 'content_type','label' => _l('content type'), 'options' => $list_content_types, 'value' => isset($data) ? $data->content_type : '','input_attr' => ['data-init-plugin' => 'select2']]) !!}
                                {!! dja_form_input(['type' => 'text', 'name' => 'link', 'label' => _l("link"), 'value' => isset($data) ? $data->link : ""]) !!}
                                {!! dja_form_input(['type' => 'file', 'name' => 'file', 'label' => _l("file"), "hint" => (isset($data) && $data->content_type == "file" ? "Leave it blank if you doesn't want to change it" : ''),'value' => '']) !!}

                                {!! dja_form_input(['type' => 'textarea', 'input_attr' => ['rows' => '3'], 'name' => 'content', 'label' => _l("content"), 'value' => isset($data) ? $data->content : ""]) !!}

                            </div>
                            <div class="col-md-12">
                                @if(isset($data))
                                <button type="button" onclick="$('.form-delete').submit()" class="btn btn-danger m-t-20">
                                    <i class="fas fa-trash m-r-10"></i>Delete
                                </button>
                                @endif
                                <div class="pull-right m-t-20">
                                    <a href="{{ route('resolution.index') }}" class="btn btn-default m-r-10"><i class="fa fa-times m-r-10"></i>{{ _l('cancel') }}</a>
                                    <button type="submit" class="btn btn-success"><i class="fa fa-check m-r-10"></i>{{ _l('save') }}</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@if(isset($data))
<form class="form-delete" action="{{route('resolution.destroy', $data->id)}}" method="post">
    @method("DELETE")
    @csrf
</form>
@endif
@endsection

@push("css")
<link rel="stylesheet" href="{{asset('assets/plugins/switchery/css/switchery.min.css')}}">
<link rel="stylesheet" href="{{asset('assets/plugins/flatpickr/dist//flatpickr.min.css')}}">
@endpush


@push("scripts")
<script type="text/javascript" src="{{ asset("assets/plugins/bootstrap-select2/select2.min.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-validation/js/jquery.validate.min.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/inputmask/dist/jquery.inputmask.bundle.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/inputmask/dist/inputmask/inputmask.numeric.extensions.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/switchery/js/switchery.min.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/ckeditor/ckeditor.js") }}"></script>
<script type="text/javascript" src="{{asset('assets/plugins/flatpickr/dist//flatpickr.min.js')}}"></script>
<script type="text/javascript" src="{{ asset("assets/js/form.js") }}"></script>


<script>
    function change_content_type() {
        if ($("#content_type").val() == "papers") {
            $("#content").closest(".form-group").slideDown()
            $("#link").closest(".form-group").slideUp()
            $("#file").closest(".form-group").slideUp()
        } else if ($("#content_type").val() == "link") {
            $("#link").closest(".form-group").slideDown()
            $("#content").closest(".form-group").slideUp()
            $("#file").closest(".form-group").slideUp()
        } else if ($("#content_type").val() == "file") {
            $("#file").closest(".form-group").slideDown()
            $("#content").closest(".form-group").slideUp()
            $("#link").closest(".form-group").slideUp()
        }
    }
    $(function() {
        CKEDITOR.replace("content", {
            toolbar: "toolbarGroups",
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
        });

        CKEDITOR.on('dialogDefinition', function(ev) {
            var dialogName = ev.data.name,
                dialogDefinition = ev.data.definition;
            if (dialogName === 'image') {
                dialogDefinition.removeContents('Upload');
            }
        });

        change_content_type()
        $(document).on("change", "#content_type", function(e) {
            change_content_type()
        })

        $("#form-content").on("submit", function(e) {
            e.preventDefault()

            if ($(this).validate()) {
                console.log($("#content").val())
                if ($("#content_type").val() == "papers" && CKEDITOR.instances.content.getData() == '') {
                    return toastr['error']('Content field is required.')
                }
                if ($("#content_type").val() == "file" && !$("#file")[0].files.length && '{{isset($data) && $data->content_type == "file" ? "yes" : "no"}}' == 'no') {
                    return toastr['error']('File field is required.')
                }
                if ($("#content_type").val() == "link" && $("#link").val() == "") {
                    return toastr['error']('Link field is required.')
                }
                if ($("#content_type").val() == "link" && !isValidHttpUrl($("#link").val())) {
                    return toastr['error']('Link is not valid.')
                }

                $(this).off("submit")
                $(this)[0].submit()
            }
        })
    });
</script>
@endpush

resources/views/resolution/table.blade.php
@extends('layouts.master')

@section("breadcrumb")
{!! dja_breadcrumb([route("home") => _l("dashboard"), "" => $title]) !!}
@endsection

@section('content')
<div class="container-fluid container-fixed-lg">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                @if(list_permit(['resolution.add']))
                <div class="panel-heading">
                    <a href="{{ route('resolution.create') }}" class="btn btn-primary">
                        <i class="fa fa-plus m-r-10"></i> {{$title}}
                    </a>
                </div>
                @endif
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            {!! $table !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('css')
<link rel="stylesheet" href="{{ asset("assets/plugins/jquery-datatable/extensions/FixedColumns/css/dataTables.fixedColumns.min.css") }}">
<link rel="stylesheet" href="{{ asset("assets/plugins/jquery-datatable/extensions/Buttons/css/buttons.bootstrap.css") }}">
<link rel="stylesheet" href="{{ asset("assets/plugins/datatables-responsive/css/datatables.responsive.css") }}" media="screen">
<link rel="stylesheet" href="{{ asset("assets/plugins/bootstrap-datepicker/css/datepicker.css") }}">
@endpush

@push('scripts')
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/media/js/jquery.dataTables.min.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/TableTools/js/dataTables.tableTools.min.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/media/js/dataTables.bootstrap.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/Bootstrap/jquery-datatable-bootstrap.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/Buttons/js/dataTables.buttons.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/Buttons/js/buttons.print.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/Buttons/js/buttons.flash.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/Buttons/js/buttons.html5.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/JSZip/jszip.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/pdfmake/pdfmake.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/jquery-datatable/extensions/pdfmake/vfs_fonts.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/datatables-responsive/js/datatables.responsive.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/datatables-responsive/js/lodash.min.js") }}"></script>

<script type="text/javascript" src="{{ asset("assets/plugins/bootstrap-select2/select2.min.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js") }}"></script>
<script type="text/javascript" src="{{ asset("assets/js/form.js") }}"></script>

<script>
    $(function() {
        dja_datatable("{{ route('resolution.table') }}");
    })
</script>
@endpush